- name: Create resultsdb namespace
  k8s:
    api_version: v1
    kind: Namespace
    name: "{{ resultsdb_namespace }}"
    state: present
    wait: true

- include_tasks: backend.yml
  tags:
    - resultsdb-backend

- include_tasks: frontend.yml
  tags:
    - resultsdb-frontend
