apiVersion: v1
kind: Route
metadata:
  name: "resultsdb-api"
  namespace: "{{ resultsdb_namespace }}"
  labels:
    app: resultsdb
spec:
{% if resultsdb_host  %}
  host: {{ resultsdb_host }}
{% endif %}
  path: /api
  port:
    targetPort: api
  to:
    kind: Service
    name: "resultsdb-api"
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
