apiVersion: v1
kind: Service
metadata: 
  name: "resultsdb-api"
  namespace: "{{ resultsdb_namespace }}"
  labels:
    app: resultsdb
spec:
  selector:
    app: resultsdb
    service: api
  ports:
    - name: api
      port: 5001
      targetPort: 5001
