apiVersion: v1
kind: ConfigMap
metadata:
  name: "resultsdb-frontend-httpd-config"
  namespace: "{{ resultsdb_namespace }}"
  labels:
    app: resultsdb
    service: web
data:
  resultsdb_frontend.conf: |-
    RequestHeader unset X-Forwarded-Host
    WSGIDaemonProcess resultsdb_frontend user=apache group=apache threads=5
    WSGIScriptAlias / /usr/share/resultsdb_frontend/resultsdb_frontend.wsgi
    WSGISocketPrefix /tmp/wsgi
    
    <Directory /usr/share/resultsdb_frontend>
        WSGIProcessGroup resultsdb_frontend 
        WSGIApplicationGroup %{GLOBAL}
        WSGIScriptReloading On
    
        Order deny,allow
        Allow from all
        <IfModule mod_authz_core.c>
            # Apache 2.4
            Require all granted
        </IfModule>
        <IfModule !mod_auth_core.c>
          Order allow,deny
          Allow from all
        </IfModule>
    </Directory> 
