apiVersion: v1
kind: Secret
metadata:
  name: resultsdb-frontend-app-config
  namespace: "{{ resultsdb_namespace }}"
  labels:
    app: resultsdb
    service: web
stringData:
  settings.py: |-
    import os    
    
    RDB_URL = '{{ resultsdb_frontend_api_url }}'
    SECRET_KEY = '{{ resultsdb_frontend_app_secret }}'
    FILE_LOGGING = False
    LOGFILE = '/var/log/resultsdb_frontend/resultsdb_frontend.log'
    SYSLOG_LOGGING = False
    STREAM_LOGGING = True
