apiVersion: v1
kind: Service
metadata: 
  name: "resultsdb-frontend"
  namespace: "{{ resultsdb_namespace }}"
  labels:
    app: resultsdb
    service: web
spec:
  selector:
    app: resultsdb
    service: web
  ports:
    - name: web
      port: 5002
      targetPort: 5002
