apiVersion: v1
kind: Route
metadata:
  name: "resultsdb-test-api"
  namespace: "{{ resultsdb_namespace }}"
  labels:
    app: resultsdb
spec:
  port:
    targetPort: api
  to:
    kind: Service
    name: "resultsdb-api"
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
