apiVersion: v1
kind: Secret
metadata:
  name: "resultsdb-config"
  namespace: "{{ resultsdb_namespace }}"
  labels:
    app: resultsdb
stringData:
  settings.py: |-
    SECRET_KEY = '{{ resultsdb_secret_key }}'
    SQLALCHEMY_DATABASE_URI = '{{ resultsdb_database_uri }}'
    FILE_LOGGING = False
    LOGFILE = '/var/log/resultsdb/resultsdb.log'
    SYSLOG_LOGGING = False
    STREAM_LOGGING = True
    RUN_HOST= '0.0.0.0'
    RUN_PORT = 5001
    MESSAGE_BUS_PUBLISH = True
    MESSAGE_BUS_PUBLISH_TASKOTRON = True
    MESSAGE_BUS_PLUGIN = 'fedmsg'
    MESSAGE_BUS_KWARGS = {'modname': 'resultsdb'}
    ADDITIONAL_RESULT_OUTCOMES = {{ resultsdb_additional_result_outcomes }}
  .htpasswd: |-
    {{ resultsdb_httpd_username }}:{{ resultsdb_httpd_password }}
